### ISSUE TITLE
Your video isn't public!

### ISSUE THREAD

**Issue by baitisj** [chrisarg0/NarcanApp#3]
Hi Chrisarg0:

Fellow FDA naloxone programmer here...

I noticed that https://youtu.be/I-zUzVe5e2Y is set to private sharing -- the FDA might have a hard time judging your entry! Best of luck!

**Comment by chrisarg0** [comment]
@baitisj I think it was still uploading at the time you tried viewing it. Should be public now. Best of luck!

**Comment by baitisj** [comment]
Yep, it's there. Awesome!
